project_id = "cketdqusxoymxbrxbkez"

[functions.create-zoom-meeting]
verify_jwt = true

[functions.create-appointment]
verify_jwt = false

[functions.fetch-calendar-events]
verify_jwt = false

[functions.get-capacity-status]
verify_jwt = false